language: php
php:
  - '7.2.30'

services:
    - mysql

before_script:
    - composer install
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test

script:
   - vendor/bin/phpunit
